<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use TCG\Voyager\Models;


class Category extends Models\Category
{

    public function getName(){
        return __('categories.'.$this->slug);
    }

    public function posts()
    {
        return parent::posts(); // TODO: Change the autogenerated stub
    }
}
